/**
 * The generate-auto-files script updates the `*.auto.yml` files in the
 * `projects` folder.
 *
 * Command usage:
 * tsx scripts/generate-auto-files.ts [projectId]
 *
 * ... where projectId is optional and asks to generate the auto file for a
 * specific project file.
 */

import fs from "node:fs";
import path from "node:path";
import { loadProjects } from "./load-projects.ts";
import { compileProjectInfo } from "./compile-project-info.ts";
import { KeyOrder } from "./key-order.ts";
import YAML from "yaml";

const projectId = process.argv[2] ? process.argv[2] : null;
const projects = loadProjects({ excludeAuto: true });

for (const [id, project] of Object.entries(projects)) {
  if (projectId && id !== projectId) {
    continue;
  }
  const autoInfo = await compileProjectInfo(project);
  const info = {};
  for (const [key, value] of Object.entries(autoInfo)) {
    if (project[key]) {
      if (Array.isArray(project[key])) {
        if (
          project[key].length === value.length &&
          project[key].every((v, i) => value[i] === v)
        ) {
          console.warn(`- Key ${key} could be dropped from ${id}.yml`);
        }
      } else if (project[key].trim() === value) {
        console.warn(`- Key ${key} could be dropped from ${id}.yml`);
      }
    } else if (key !== "id") {
      info[key] = value;
    }
  }

  const contents =
    `# Generated from: ${id}.yml
# Do not edit this file by hand. Edit the source file instead!

` + YAML.stringify(info, KeyOrder);

  fs.writeFileSync(path.join("projects", `${id}.auto.yml`), contents, "utf8");
}
