name: Add the suggested project

on:
  issue_comment:
    # Details for types below can be found at:
    # https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads?actionType=edited#issues
    types:
      # Job triggered when an issue comment is created (or edited)
      - created
      - edited

jobs:
  check:
    name: Check user permission
    runs-on: ubuntu-latest
    outputs:
      status: ${steps.checkUser.outputs.user-permission}
    steps:
      - id: checkUser
        name: Check user permission
        uses: actions-cool/check-user-permission@v2.3.0

  prepare:
    name: Create pull request if needed
    runs-on: ubuntu-latest
    needs: check
    # TODO: Consider allowing 'write' permissions as well
    if: ${{ needs.check.outputs.status == 'admin' }}
    steps:
      - name: Setup node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: main

      - name: Install dependencies
        run: npm ci

      - name: Check suggested project
        run: npx tsx scripts/check-suggested-project.ts $NUMBER --add > res.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUMBER: ${{ github.event_name == 'workflow_dispatch' && inputs.issueNumber || github.event.issue.number }}

      - name: Commit updates
        run: |
          git config user.name "add-suggested-project bot"
          git config user.email "<>"
          git add projects
          git commit -F res.md

      - name: Push changes
        uses: ad-m/github-push-action@v1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
