name: Build new index.json file

on:
  schedule:
    # Every 12 hours every day
    - cron: "40 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "npm"

      - name: Setup environment
        run: npm ci

      - name: Make sure project info is complete
        run: npm run test:projects

      - name: Build new index file from YAML files
        run: npm run build

      - name: Make sure updated list is correct
        run: npm run test:list

      - name: Commit updates
        run: |
          git config user.name "build-index bot"
          git config user.email "<>"
          git commit -m "Update index.json" -a || true

      - name: Push changes
        uses: ad-m/github-push-action@v1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
